### ISSUE TITLE
Purpose of TutorialImageView.java? 

### ISSUE THREAD

**Issue by rayliverified** [msayan/tutorial-view#1]
This class appears to have no function. Why not use and ImageView instead? 
Great library BTW, thanks for sharing!

**Comment by msayan** [comment]
it's forgotten class sorry for that,
I deleted it in this [commit](https://github.com/msayan/tutorial-view/commit/41c422127143e21d5509dcee6c8c773cf88a712a)

**Comment by rayliverified** [comment]
Nice :) Again, great library!
