### ISSUE TITLE
Throws error when swipe/press next button

### ISSUE THREAD

**Issue by vjjustin** [msayan/tutorial-view#12]
I have created a sample implementation. The below is the complete code. When I load I can see the first page and when I swipe I can see the next page till I lift my finger of the screen. Then the app breaks. I believe it is something to do with currentFragmentPosition but I don't know what to do or how to resolve. Can someone help?

`package .ui.welcome

import android.Manifest
import android.os.Bundle
import android.support.v4.content.ContextCompat
import com.hololo.tutorial.library.Step
import com.hololo.tutorial.library.TutorialActivity
import matrimony.matrimony.R

class Introduction: TutorialActivity() {
    override fun currentFragmentPosition(position: Int) {
        //super.currentFragmentPosition(position)
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        addFragment(Step.Builder().setTitle("This is header")
                .setContent("This is content")
                .setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary)) // int background color
                .setDrawable(R.drawable.avatar) // int top drawable
                .setSummary("This is summary")
                .build())
        addFragment(Step.Builder().setTitle("This is header")
                .setContent("This is content")
                .setBackgroundColor(ContextCompat.getColor(this, R.color.colorAccent)) // int background color
                .setDrawable(R.drawable.avatar) // int top drawable
                .setSummary("This is summary")
                .build())
        addFragment(Step.Builder().setTitle("This is header")
                .setContent("This is content")
                .setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary)) // int background color
                .setDrawable(R.drawable.avatar) // int top drawable
                .setSummary("This is summary")
                .build())
        addFragment(Step.Builder().setTitle("This is header")
                .setContent("This is content")
                .setBackgroundColor(ContextCompat.getColor(this, R.color.colorAccent)) // int background color
                .setDrawable(R.drawable.avatar) // int top drawable
                .setSummary("This is summary")
                .build())

    }

    override fun finishTutorial() {
        // Your implementation
        finish()
    }
}`

**Comment by msayan** [comment]
Can you paste the crash log?

**Comment by vjjustin** [comment]
Ok, I am sorry. It is working fine now!!
Error was because the TODO (which was auto added) was not commented out!!! My bad. 
I was pasting the log here and then I saw the line number mentioned in introduction.kt that pointed to TODO.

Thank you!!
