### ISSUE TITLE
Start Another Activity

### ISSUE THREAD

**Issue by SefuZeph** [msayan/tutorial-view#2]
I want to start another activity from this library. Please Help. Thanks!

**Comment by msayan** [comment]
@CodeApeZeph Now you can use override method below

```java

    @Override
    public void finishTutorial() {
        // Your implementation
    }

```

**Comment by msayan** [comment]
i think it's ok now

**Comment by SefuZeph** [comment]
Thank You very much, It's working perfectly!

**Comment by fajarhaiqal2** [comment]
I want open activity on tutorial finish,What should I do?

**Comment by msayan** [comment]
@fajarhaiqal2  you can add this method on your Activity.

```java
@Override
    public void finishTutorial() {
        Intent intent = new Intent(this, YourActivity.class);
        startActivity(intent);
    }
```

**Comment by fajarhaiqal2** [comment]
Thanks

Pada tanggal Kam, 8 Nov 2018 12.56, Mehmet Ayan <notifications@github.com>
menulis:

**Comment by Jaisriram3600** [comment]
Override method finishTutorial not working !!
shows"Method does not override method  from its superclass"
