### ISSUE TITLE
How to make sure this runs only once and not everytime we launch the app?

### ISSUE THREAD

**Issue by vivek9746** [msayan/tutorial-view#4]

**Comment by msayan** [comment]
You need to implement your logic like

   if (pref.getBoolean("openFirst", true)) {
            startActivity(Intent(this, TutorialActivity::class.java))
            finish()
        } else {
}

**Comment by msayan** [comment]
Did you resolve your issue?

**Comment by vivek9746** [comment]
Yes, thank you. @msayan   :)
