### ISSUE TITLE
Next/Prev/Finish/Cancel buttons text takes one swap to load

### ISSUE THREAD

**Issue by zdunex25** [msayan/tutorial-view#6]
I have to swipe between two fragments for custom strings to load, by default I always see English ones.

**Comment by smhdk** [comment]
Hi @zdunex25 ,
You can use thats methotds for change prev,next,cancel and finish text.

setPrevText(text); // Previous button text
setNextText(text); // Next button text
setFinishText(text); // Finish button text
setCancelText(text); // Cancel button text

**Comment by msayan** [comment]
Fixed #7

**Comment by zdunex25** [comment]
After update I cannot Run anymore:
_error: Tutorial is not abstract and does not override abstract method currentFragmentPosition(int) in CurrentFragmentListener_
When I make it abstract, runs, but activity force closes on start.

**Comment by zdunex25** [comment]
Ok, forget it, works fine. However you might want to update **Usage** with currentFragmentPosition(int). Thanks!

**Comment by vjjustin** [comment]
How did you solve this???
error: Tutorial is not abstract and does not override abstract method currentFragmentPosition(int) in CurrentFragmentListener

I get the same error. Can you pelase help?

**Comment by vjjustin** [comment]
As in, I get error when I swipe next. I did override currentFragementPosition, but nothing is added inside. Do we need to do something or call something?

**Comment by zdunex25** [comment]
I am sorry I cannot remember what I was doing wrong.
